### ISSUE TITLE
Error "panic: runtime error: slice bounds out of range" when using option --sshconfig

### ISSUE THREAD

**Issue by hanthethanh** [pressly/sup#136]
Hello,

when I tried the --sshconfig option I got an error as below:

```
$ sup --sshconfig=~/.ssh/config vps ping     
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.resolvePath(0x0, 0x0, 0xc4200165b0, 0xc)
	/Users/vojtechvitek/go/src/github.com/pressly/sup/cmd/sup/main.go:191 +0x105
main.main()
	/Users/vojtechvitek/go/src/github.com/pressly/sup/cmd/sup/main.go:304 +0xd1d
```

Am I missing something, or this is a bug?

btw,  `sup --help` show this:
```
  -sshconfig string
    	Read SSH Config file, ie. ~/.ssh/config file
```
Note that there are only 1 hyphen. I tried with both 1 & 2 hyphens and the result is the same.

**Comment by pabloalvarezcap** [comment]
Write what release/commit are you using.

**Comment by hanthethanh** [comment]
I followed the installation instruction on github page:
`go get -u github.com/pressly/sup/cmd/sup`

Currently it is:
```
$ sup -v
0.5
```

**Comment by pabloalvarezcap** [comment]
At line 284 there is: `confHosts, err := sshconfig.ParseSSHConfig(resolvePath(sshConfig))`
confHosts will be of type `[]*SSHHost`, as we can see [here](https://github.com/mikkeloscar/sshconfig/blob/056592cb6962e83d208af2e58d90c3759ba09825/parser.go#L42) if there is not IdentityFile on ssh config file, it will not be initialitated, so, at  line 304 when the program calls to `resolvePath()` passing `conf.IdentityFile` as argument; there is a panic at 191, because we are doing:
`if path[:2] == "~/" {`
That is a error, because the length of path will be 0.

@VojtechVitek see that.

**Comment by pabloalvarezcap** [comment]
@hanthethanh you could try to go to append at the beginning of the function `resolvePath` and add:
`if len(path) == 0 {
    return ""
}`
or:
``if path == "" {
    return ""
}``

**Comment by pabloalvarezcap** [comment]
#137

**Comment by hanthethanh** [comment]
thank you, it works now.
