### ISSUE TITLE
IS THIS PROJECT ABANDONED?

### ISSUE THREAD

**Issue by insign** [pressly/sup#179]
Sorry for using this place. But the last release is from 2018. And Pressly looks was acquired. So.... What's is happening?

**Comment by VojtechVitek** [comment]
Hi,
 I don't have the time to maintain this project anymore. Any enthusiasts to take over?

**Comment by insign** [comment]
Well, I could take over the project, mainly to review pull requests and some adjustments, but since it is owned by a company which was acquired, are you willing to transfer ownership?

**Comment by VojtechVitek** [comment]
Sup is MIT licensed. There's no company lock-in besides having to keep the original copyright in the LICENSE file (can be amended).

I'm willing to add contributors to this project and/or move this repo to its own community organization if there's enough interest eventually.

However, I can't just transfer the repo to someone I don't really know yet -- no offence!

**Comment by insign** [comment]
@VojtechVitek np, probably would be weird just transfer it. I loved the idea behind the project. Maybe you by yourself should at least review the PR and maybe implement some tests to easily approve them.

**Comment by mtroback** [comment]
@insign I just found myself with a bunch of RPi on which I need to do just about the same commands over and over again. This project seems to fit my needs but it desperately would need the waiting PRs merged in order to work. Maybe it is easier for Vojtech whom obviously doesn't have time (which I totally understands) if you could take the contributor role and merge anything that looks good and then we, the users, needs to get back if something isn't working (with no hard feelings)?

**Comment by VojtechVitek** [comment]
I think I'll be able to merge PRs with decent high-level description and at least 2 reviews and working test-cases.

I case of new features, I'd appreciate some discussion up-front in Issues, so we don't waste anyone's development time too early.
